# Generated by Django 5.0.4 on 2024-04-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_alter_transfer_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='id_t',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='qr_code',
        ),
    ]
