# Generated by Django 5.0.4 on 2024-04-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_remove_qr_id_t_remove_qr_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
