# Generated by Django 5.0.4 on 2024-04-18 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_delete_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qr',
            name='wh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh', to='Production.wh'),
        ),
    ]
