# Generated by Django 5.0.4 on 2024-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0006_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=1, max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
    ]
