# Generated by Django 5.0.4 on 2024-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.IntegerField(verbose_name='Tenant ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_unit_name', models.CharField(max_length=255, verbose_name='Product Unit Name')),
                ('unit_name', models.CharField(max_length=100, verbose_name='Unit Name')),
                ('remaining_quantity', models.IntegerField(default=0, verbose_name='Remaining Quantity')),
                ('relative_remaining_quantity', models.IntegerField(default=0, verbose_name='Relative Remaining Quantity')),
                ('tier_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tier Price')),
                ('created', models.DateTimeField(verbose_name='Created Date')),
                ('modified', models.DateTimeField(verbose_name='Modified Date')),
                ('picture', models.URLField(verbose_name='Picture URL')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('unit_fraction', models.PositiveIntegerField(default=1, verbose_name='Unit Fraction')),
                ('old_cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old Cost Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('default', models.BooleanField(default=True, verbose_name='Default')),
                ('sync_quantity_salla', models.BooleanField(default=False, verbose_name='Sync Quantity with Salla')),
                ('quantity_salla', models.IntegerField(default=0, verbose_name='Quantity in Salla')),
                ('auto_add', models.BooleanField(default=False, verbose_name='Auto Add')),
                ('item_code', models.CharField(max_length=100, verbose_name='Item Code')),
                ('related_item_code', models.JSONField(default=list, verbose_name='Related Item Codes')),
                ('product', models.IntegerField(verbose_name='Product ID')),
                ('unit', models.IntegerField(verbose_name='Unit ID')),
            ],
        ),
    ]
