# Generated by Django 5.0.4 on 2024-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0009_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='auto_add',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='default',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='item_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='old_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='picture',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='product_unit_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='quantity_salla',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='related_item_code',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='relative_remaining_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='remaining_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='sync_quantity_salla',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='tenant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='tier_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='unit_fraction',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
