# Generated by Django 5.0.4 on 2024-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0012_alter_product_unit_related_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='related_item_code',
            field=models.JSONField(default=list),
        ),
    ]
