# Generated by Django 5.0.4 on 2024-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0013_alter_product_unit_related_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='auto_add',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='old_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='product_unit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='quantity_salla',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='related_item_code',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='relative_remaining_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='remaining_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='sync_quantity_salla',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='tenant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='tier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='unit_fraction',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
