# Generated by Django 5.0.4 on 2024-04-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0014_alter_product_unit_auto_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='productunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.product_unit'),
        ),
    ]
