# Generated by Django 5.0.4 on 2024-04-27 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='productunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productunit'),
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='unit_frac',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productunit',
            name='auto_add',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='old_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productunit',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productunit',
            name='product_unit_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productunit',
            name='quantity_salla',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='related_item_code',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productunit',
            name='relative_remaining_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='remaining_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sync_quantity_salla',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='tenant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='tier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit_fraction',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='item_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='product_unit',
        ),
        migrations.DeleteModel(
            name='unit_frac',
        ),
    ]
