# Generated by Django 5.0.4 on 2024-04-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productunit_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='related_item_code',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
