# Generated by Django 5.0.4 on 2024-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productunit_related_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='related_item_code',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
