# Generated by Django 5.0.4 on 2024-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_productunit_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='item_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='sku',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
