# Generated by Django 5.0.4 on 2024-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_productunit_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='sku',
            field=models.CharField(blank=True, null=True),
        ),
    ]
