# Generated by Django 5.0.4 on 2024-04-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_productunit_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='picture',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='sku',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
