# Generated by Django 5.0.4 on 2024-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_productunit_picture_alter_productunit_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
