# Generated by Django 5.0.4 on 2024-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_qr_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='generate_qr_flag',
            field=models.BooleanField(default=True),
        ),
    ]
