# Generated by Django 5.0.4 on 2024-05-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_track_transfer_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferDetail',
        ),
        migrations.DeleteModel(
            name='Transferr',
        ),
    ]
