# Generated by Django 5.0.3 on 2024-03-28 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_input_created_at_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
