# Generated by Django 5.0.3 on 2024-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_input_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
