# Generated by Django 5.0.3 on 2024-03-28 06:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='productunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.unit')),
            ],
        ),
    ]
