# Generated by Django 5.0.3 on 2024-03-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_unit_frac'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='unit_frac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.unit_frac'),
            preserve_default=False,
        ),
    ]
