# Generated by Django 5.0.3 on 2024-03-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_productunit_unit_frac'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_units/'),
        ),
    ]
