# Generated by Django 5.0.3 on 2024-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_productunit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
