# Generated by Django 5.0.3 on 2024-03-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_productunit_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='wh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Smacc_Code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productunit',
            name='item_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
