# Generated by Django 5.0.3 on 2024-03-28 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_wh_alter_productunit_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('productunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productunit')),
                ('wh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.wh')),
            ],
        ),
    ]
