# Generated by Django 5.0.3 on 2024-03-28 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_from', to='website.wh')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_to', to='website.transportgroup')),
            ],
        ),
    ]
