# Generated by Django 5.0.3 on 2024-03-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_transportgroup_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transport_images/')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.transport')),
            ],
        ),
    ]
