# Generated by Django 5.0.3 on 2024-03-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_productpicked1_smaccfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicked1',
            name='smaccTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smacc_to', to='website.smaccgroup'),
        ),
    ]
