# Generated by Django 5.0.3 on 2024-03-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_productpicked1_smaccto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpicked1',
            name='smaccFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smacc_from', to='website.wh'),
        ),
        migrations.AlterField(
            model_name='productpicked1',
            name='smaccTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smacc_to', to='website.wh'),
        ),
        migrations.DeleteModel(
            name='smaccGroup',
        ),
    ]
